console.log("Well, I'm here. What are your next two wishes?")
console.log("")
console.log("")
console.log("")
console.log("BIRTHDAY LETTER: https://docs.google.com/document/d/1HRvfuNO_hZWvDhMj7OviF4tHgwKkI4YloRQRaxmlmlA/edit?usp=sharing")
console.log("")
console.log("")
console.log("")
console.log("A VIDDY MESSAGE: ")